# Generated by Django 5.1.4 on 2025-03-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('thaluk', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message', models.TextField()),
                ('current_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CampAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_message', models.TextField(max_length=50)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
        migrations.CreateModel(
            name='CampNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.TextField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('camp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
        migrations.CreateModel(
            name='FundAllocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fund')),
                ('full_name', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('ration_card_no', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('other_details', models.TextField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('camp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='FundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=100)),
                ('card_no', models.IntegerField(default=0)),
                ('expiring_date', models.CharField(max_length=10)),
                ('cvv_no', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('req_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fundallocationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_sub', models.CharField(max_length=100)),
                ('complaint', models.TextField(max_length=500)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(blank=True, max_length=500, null=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='CampUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='camp')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('thaluk', models.CharField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('camp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('other_details', models.TextField()),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('station_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.police')),
                ('public_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.public')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq', models.TextField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
                ('public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.public')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=30)),
                ('vehicle_num', models.CharField(max_length=15)),
                ('missing_place', models.CharField(max_length=20)),
                ('missing_date', models.CharField(max_length=10)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.police')),
                ('public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('aadhar_no', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=15)),
                ('allocation', models.CharField(blank=True, max_length=100, null=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.AddField(
            model_name='fundallocationmodel',
            name='volunteer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(blank=True, max_length=30, null=True)),
                ('duty', models.TextField()),
                ('curr_date', models.DateField(auto_now_add=True)),
                ('camp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
                ('volunteer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_date', models.DateField(auto_now_add=True)),
                ('duty_status', models.CharField(default='Not Scheduled', max_length=100)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_volunteers', models.IntegerField(default=0)),
                ('totalallocated', models.IntegerField(default=0)),
                ('volunteer_details', models.TextField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
    ]
